version: '3.8'

services:
  db:
    image: postgres:18
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  justflow:
    image: justnz/justflow:latest
    depends_on:
      - db
    ports:
      - "3000:3000" # JustFlow frontend
      - "8080:8080" # JustFlow backend
    volumes:
      - justflow_data:/etc/justflow
    entrypoint: ["/bin/sh", "-c", "until pg_isready -h db -p 5432 -U postgres; do sleep 1; done; exec ./justflow-backend --config /etc/justflow/config.yaml & exec node /app/server.js"]

volumes:
  db_data:
  justflow_data: