---

LogLevel: info

Port: 8080

Database:
  Server: localhost
  Port: 5432
  Name: postgres
  User: postgres
  Password: postgres

Encryption:
  Enabled: true
  # maximum 32 characters
  Key: null

JWT:
  Secret: null
