name: Build Image Manual Branch

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build and release'
        required: true
        default: 'develop'
      component:
        description: 'Component to build'
        required: true
        default: 'all'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Build Frontend Docker Image
        if: ${{ github.event.inputs.component == 'all' || github.event.inputs.component == 'frontend' }}
        run: docker build apps/frontend --file apps/frontend/Dockerfile --tag ghcr.io/justlabv1/justflow:frontend-manual-${{ github.sha }}

      - name: Build Backend Docker Image
        if: ${{ github.event.inputs.component == 'all' || github.event.inputs.component == 'backend' }}
        run: docker build apps/backend --file apps/backend/Dockerfile --tag ghcr.io/justlabv1/justflow:backend-manual-${{ github.sha }}

      - name: Build justFlow Docker Image
        if: ${{ github.event.inputs.component == 'all' || github.event.inputs.component == 'justflow' }}
        run: docker build . --file Dockerfile --tag ghcr.io/justlabv1/justflow:manual-${{ github.sha }}

      - name: Build Runner Docker Image
        if: ${{ github.event.inputs.component == 'all' || github.event.inputs.component == 'runner' }}
        run: docker build . --file apps/runner/Dockerfile --tag ghcr.io/justlabv1/runner:manual-${{ github.sha }}

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker Images
        run: |
          if [[ "${{ github.event.inputs.component }}" == "all" || "${{ github.event.inputs.component }}" == "frontend" ]]; then
            docker push ghcr.io/justlabv1/justflow:frontend-manual-${{ github.sha }}
          fi
          if [[ "${{ github.event.inputs.component }}" == "all" || "${{ github.event.inputs.component }}" == "backend" ]]; then
            docker push ghcr.io/justlabv1/justflow:backend-manual-${{ github.sha }}
          fi
          if [[ "${{ github.event.inputs.component }}" == "all" || "${{ github.event.inputs.component }}" == "justflow" ]]; then
            docker push ghcr.io/justlabv1/justflow:manual-${{ github.sha }}
          fi
          if [[ "${{ github.event.inputs.component }}" == "all" || "${{ github.event.inputs.component }}" == "runner" ]]; then
            docker push ghcr.io/justlabv1/runner:manual-${{ github.sha }}
          fi
